# Autogenerated file
def render(title="CO2 Monitor", content=""):
    yield """<!DOCTYPE html>
<html>
<head>
    <title>"""
    yield str(title)
    yield """</title>
    <meta charset=\"utf-8\">
    <style>
        body """
    yield """{ font-family: sans-serif; margin: 20px; background: #fafafa; }
        h1 """
    yield """{ color: #333; }
        meter """
    yield """{ width: 200px; height: 20px; }
        table """
    yield """{ border-collapse: collapse; width: 100%; margin-top: 20px; }
        th, td """
    yield """{ border: 1px solid #ddd; padding: 8px; text-align: left; }
        th """
    yield """{ background-color: #f2f2f2; }
        a """
    yield """{ color: #0066cc; text-decoration: none; }
        a:hover """
    yield """{ text-decoration: underline; }
        .metric """
    yield """{ background: #fff; padding: 15px; margin: 10px 0; border: 1px solid #ddd; border-radius: 5px; }
    </style>
</head>
<body>
    <h1>"""
    yield str(title)
    yield """</h1>
    """
    yield str(content)
    yield """
</body>
</html>"""
