# Autogenerated file
def render(current_co2=None, last_measurement_time="", current_time="", log_files=[]):
    yield """<!DOCTYPE html>
<html>
<head>
    <title>CO2 Monitor</title>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <style>
        body """
    yield """{ 
            font-family: sans-serif; 
            margin: 20px; 
            background: #f5f5f5;
        }
        .container """
    yield """{ 
            max-width: 800px; 
            margin: 0 auto; 
            background: white; 
            padding: 20px;
            border-radius: 5px;
        }
        h1 """
    yield """{ 
            color: #333; 
            margin: 0 0 10px 0;
        }
        .co2-display """
    yield """{
            background: white;
            text-align: center;
            padding: 15px;
            margin: 10px 0;
            border: 2px solid #4caf50;
            border-radius: 5px;
        }
        .co2-display.warning """
    yield """{
            border-color: #f44336;
        }
        .co2-display.danger """
    yield """{
            border-color: #d32f2f;
            border-width: 3px;
        }
        .co2-value """
    yield """{
            font-size: 2.5em;
            font-weight: bold;
            margin: 5px 0;
        }
        .co2-value.warning """
    yield """{
            color: #f44336;
        }
        .co2-value.danger """
    yield """{
            color: #d32f2f;
        }
        .co2-status """
    yield """{
            font-size: 1.1em;
            margin: 5px 0;
        }
        meter """
    yield """{
            width: 200px;
            height: 20px;
        }
        .details """
    yield """{
            list-style: none;
            padding: 10px 0;
            margin: 0;
            font-size: 0.9em;
            color: #666;
        }
        .details li """
    yield """{
            margin: 3px 0;
        }
        a """
    yield """{
            color: #4caf50;
            text-decoration: none;
        }
        a:hover """
    yield """{
            text-decoration: underline;
        }
        .api-link """
    yield """{
            display: inline-block;
            background: #4caf50;
            color: white;
            padding: 8px 16px;
            margin: 10px 0;
            border-radius: 3px;
        }
        .api-link:hover """
    yield """{
            background: #45a049;
            text-decoration: none;
        }
        h2 """
    yield """{
            color: #333;
            margin: 20px 0 10px 0;
            font-size: 1.2em;
        }
        .table-container """
    yield """{
            overflow-x: auto;
            margin: 10px 0;
        }
        table """
    yield """{
            width: 100%;
            min-width: 600px;
            border-collapse: collapse;
            background: white;
        }
        th """
    yield """{
            background: #4caf50;
            color: white;
            padding: 10px;
            text-align: left;
        }
        td """
    yield """{
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        .actions a """
    yield """{
            display: inline-block;
            padding: 4px 8px;
            margin: 1px;
            font-size: 0.8em;
            border-radius: 3px;
            white-space: nowrap;
        }
        .download """
    yield """{ background: #2196f3; color: white; }
        .delete """
    yield """{ background: #f44336; color: white; }
        .chart """
    yield """{ background: #9c27b0; color: white; }
        .waiting """
    yield """{
            text-align: center;
            padding: 20px;
            color: #666;
            font-style: italic;
        }
        @media (max-width: 600px) """
    yield """{
            body """
    yield """{ margin: 10px; }
            .container """
    yield """{ padding: 15px; }
            .co2-value """
    yield """{ font-size: 2em; }
            meter """
    yield """{ width: 150px; }
        }
    </style>
</head>
<body>
    <div class=\"container\">
        <h1>🌱 CO2 Monitor</h1>
        
        """
    if current_co2 is not None:
        yield """        <div class=\"co2-display """
        if current_co2 > 1500:
            yield """danger"""
        elif current_co2 > 1000:
            yield """warning"""
        yield """\">
            <div class=\"co2-value """
        if current_co2 > 1500:
            yield """danger"""
        elif current_co2 > 1000:
            yield """warning"""
        yield """\">"""
        yield str(current_co2)
        yield """ ppm</div>
            <div class=\"co2-status\">
                """
        if current_co2 > 1500:
            yield """                🚨 Action Required
                """
        elif current_co2 > 1000:
            yield """                💨 Increase Ventilation
                """
        else:
            yield """                👍 Excellent
                """
        yield """            </div>
            <meter value=\""""
        yield str(current_co2)
        yield """\" min=\"400\" max=\"1500\" optimum=\"450\" high=\"800\">"""
        yield str(current_co2)
        yield """ ppm</meter>
            
            <ul class=\"details\">
                <li>Updated: """
        yield str(last_measurement_time)
        yield """</li>
                <li>Current time: """
        yield str(current_time)
        yield """</li>
                <li>Sensor: <a href=\"https://sensirion.com/products/catalog/SCD40\">SCD40</a></li>
            </ul>
        </div>
        """
    else:
        yield """        <div class=\"waiting\">
            <div class=\"co2-value\">⏳</div>
            <p>Waiting for first CO2 reading...</p>
        </div>
        """
    yield """
        <a href=\"/co2\" class=\"api-link\">JSON API</a>

        <h2>Data Files</h2>
        <div class=\"table-container\">
            <table>
                <tr>
                    <th>Filename</th>
                    <th>Size</th>
                    <th>Actions</th>
                </tr>
                """
    for filename, size in log_files:
        yield """                <tr>
                    <td>"""
        yield str(filename)
        yield """</td>
                    <td>"""
        yield str(size)
        yield """ bytes</td>
                    <td class=\"actions\">
                        <a href=\"/download/"""
        yield str(filename)
        yield """\" class=\"download\">Download</a>
                        <a href=\"/delete/"""
        yield str(filename)
        yield """\" class=\"delete\" onclick=\"return confirm('Delete """
        yield str(filename)
        yield """?')\">Delete</a>
                        """
        if filename.startswith("week"):
            yield """                        <a href=\"/spark/"""
            yield str(filename)
            yield """\" class=\"chart\">Weekly Chart</a>
                        """
        else:
            yield """                        <a href=\"/spark/"""
            yield str(filename)
            yield """\" class=\"chart\">Daily Chart</a>
                        """
        yield """                    </td>
                </tr>
                """
    yield """            </table>
        </div>
        
        """
    if not log_files:
        yield """        <div class=\"waiting\">
            <p>No data files available yet</p>
        </div>
        """
    yield """    </div>
</body>
</html>"""
